title: Total Miner
description: Total Miner Files are here and free
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
exclude:  
  - ".gitignore"
  - "Gemfile"
  - "Gemfile.lock"
  - "_config.yml"
  - "jekyll-theme-hacker.gemspec"
  - ".travis.yml"
  - ".rubocop.yml"
 
  
