title: Total Miner
description: Total Miner Files are here and free
show_downloads: false
zip_url: https://github.com/forgeproject/forgeproject.github.io/archive/refs/heads/main.zip
google_analytics:
theme: jekyll-theme-hacker

 
  
